# Provides print out before closing from error
def error():
    print("\nAn Error has Occurred.")
    exit()
